name: Android CI

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create Release?'
        required: true
        type: boolean
        default: false

      draft:
        description: 'Create as draft?'
        required: true
        type: boolean
        default: true

      abi:
        description: 'Select ABI to upload'
        required: true
        type: choice
        options:
          - all
          - arm64-v8a
          - armeabi-v7a
          - x86
          - x86_64
          - universal
        default: 'all'

  pull_request:
    types: [opened, synchronize]

jobs:
  pr-build-check:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test build with Gradle
        run: ./gradlew assembleRelease

      - name: Auto-merge if build succeeds and actor is Dependabot
        if: ${{ success() && github.actor == 'dependabot[bot]' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        if: ${{ inputs.release }}
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          mkdir -p "${RUNNER_TEMP}"
          echo -n "${ENCODED_KEYSTORE}" | base64 --decode > "${RUNNER_TEMP}/panda.jks"

      - name: Create release keystore
        if: ${{ inputs.release }}
        run: |
          echo "STORE_FILE=${RUNNER_TEMP}/panda.jks" > keystore.properties
          echo "STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          echo "API_KEY=${{ secrets.API_KEY }}" >> keystore.properties

      - name: Create debug keystore
        if: ${{ !inputs.release }}
        run: |
          mkdir -p "${RUNNER_TEMP}"
          keytool -genkey -v -keystore "${RUNNER_TEMP}/debug.keystore" \
                  -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
                  -storepass android -keypass android \
                  -dname "CN=Android Debug,O=Android,C=US"

          echo "STORE_FILE=${RUNNER_TEMP}/debug.keystore" > keystore.properties
          echo "STORE_PASSWORD=android" >> keystore.properties
          echo "KEY_ALIAS=androiddebugkey" >> keystore.properties
          echo "KEY_PASSWORD=android" >> keystore.properties

      - name: Build Release APKs
        run: ./gradlew assembleRelease

      - name: Upload APKs as Artifact
        if: ${{ !inputs.release }}
        uses: actions/upload-artifact@v4
        with:
          name: echoir-${{ inputs.abi }}-apks
          path: |
            ${{ inputs.abi == 'all' && 'app/build/outputs/apk/release/*.apk' || format('app/build/outputs/apk/release/*{0}*.apk', inputs.abi) }}
          retention-days: 7

      - name: Create Release
        if: ${{ inputs.release }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(grep -A5 'defaultConfig {' app/build.gradle.kts | grep 'versionName' | awk -F '"' '{print $2}')
          gh release create "v${VERSION}" \
            --title "Echoir v${VERSION}" \
            --notes-file CHANGELOG.md \
            ${{ inputs.draft && '--draft' || '' }} \
            app/build/outputs/apk/release/*.apk
